main: com.alpsbte.plotsystemterra.PlotSystemTerra
version: 3.1
api-version: 1.12.2
name: PlotSystem-Terra
author: R3tuxn, Coppertine, SirJodelstein
softdepend: [WorldEdit, HeadDatabase]

commands:
  createplot:
    description: Creates a new plot for the PlotSystem.
    usage: /createplot
    permission: plotsystem.createplot
  pasteplot:
    description: Pastes a plot manually with specific ID
    usage: /pasteplot <ID>
    permission: plotsystem.pasteplot
  plotsystemterra:
    description: Sends info about the plugin
    usage: /plotsystemterra